In [1]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import statsmodels.formula.api as smf

In [15]:
df = pd.read_csv('https://raw.githubusercontent.com/ryupepa/Econometrica/master/python-notebooks/data-csv/Labour.csv')
df

       capital  labour     output       wage
0     2.606563     184   9.250759  43.080307
1     1.323237      91   3.664310  27.780016
2    22.093692     426  28.781516  44.467748
3    10.737851      72   4.124642  39.734710
4     1.161365      46   2.890150  34.650709
..         ...     ...        ...        ...
564   2.625403      20   1.424376  33.477545
565   1.276386      61   2.109048  26.300732
566   1.953869     117   6.241870  41.153979
567   1.318527      46   7.902237  66.720139
568   2.832391     161   6.804085  36.618435

[569 rows x 4 columns]

In [5]:
model = smf.ols(data=df, formula='output~capital+labour+wage').fit()
hat_y=model.predict()

In [6]:
hat_y

array([ 1.22906950e+01,  4.57101298e-01,  3.26713978e+01,  8.45249490e+00,
        1.15007554e+00,  4.95323301e+02,  4.96225925e-01,  2.69781742e+00,
        6.93083590e-01,  2.43757091e+00,  5.66564085e+00,  1.92791692e+00,
       -2.55367472e-01,  3.71340262e+00,  3.00062549e+00,  5.58104740e+00,
       -5.65128192e+00,  1.60377117e+01,  2.27977417e+00, -1.63642251e+00,
       -5.20310116e+00,  7.25038098e+00,  4.06867541e+00, -6.25486350e-01,
        3.32128894e+00,  4.22318186e+00,  5.97177164e+00,  6.60880530e+00,
        1.37823245e+01,  5.40857894e+00, -1.68422671e+00,  3.97020603e+00,
        1.11408840e+01, -9.36989184e-01,  9.15360522e+00, -6.27008499e-01,
        4.01437577e+00,  1.68675245e+01,  2.41409083e+00,  3.64642225e+00,
        3.49784717e+01,  5.31658996e+00,  3.26044590e+00,  1.96810268e+01,
        7.68688994e+00,  6.09158964e+00,  3.71223636e+01,  6.83356225e-01,
        5.77238852e+00,  2.03922830e+01,  3.94775369e+00,  8.78354170e+00,
        6.07147791e+01,  1.52278262e+02,  7.88775171e+00,  2.07133501e+02,
       -3.60744533e+00, -3.91912593e-02, -3.15519408e+00, -1.36787904e+00,
        1.06856916e+01,  4.57442522e+01,  2.03041597e+01,  4.45832281e+00,
       -7.15309228e-01,  7.11463113e+00, -2.17550260e-01,  6.32116243e+00,
        1.11421650e+01,  5.26782721e+01,  5.05781479e-01,  2.76544521e+01,
        4.77710711e-01,  1.01811381e+01,  6.00219705e+00,  3.36480812e+00,
        3.28328592e+00,  3.16063828e+01, -3.14241244e+00,  7.04988944e+00,
        2.35068896e+01,  5.87428376e+00, -1.33480957e-01,  2.76603961e+00,
        4.64215788e+00,  7.40464848e+01,  1.04733770e+01,  7.65112318e+00,
        2.02866954e+01,  8.69872864e+00,  1.28020820e+00,  1.02553915e+01,
        2.84398697e+00, -3.81793424e+00,  3.29313529e+00,  2.66255886e+00,
        8.79067109e+00,  1.13304361e+01,  3.39705224e+00,  1.59359752e+00,
        6.95205394e+00,  1.01593348e+01,  4.75820670e+01,  8.65431706e+00,
        8.38602855e+00,  1.14552995e+01,  3.76085485e+01,  4.46933149e+00,
        2.23040916e+01, -9.61063062e-01,  4.99870991e+00,  4.61501780e+01,
        1.01804165e+01, -2.53983908e+00,  9.48812017e+00,  9.55872787e+00,
        3.79499211e-01,  2.79596337e+01, -2.42651250e-01,  1.34451993e+01,
       -1.58978060e+00,  4.95779390e+00,  2.07523674e+01,  1.27183661e+00,
        1.19884086e+00,  1.32281462e+01,  1.44261958e+00,  3.61171132e+00,
        3.54981494e+02,  8.41502066e+00,  1.37660528e+01,  1.80843740e+00,
        1.02217955e+01,  3.83847994e+00,  3.42402327e+00,  1.27323286e+01,
        3.90729352e+00,  3.10788259e+00, -1.73287203e+00,  1.27515450e+01,
       -1.42312255e-01,  3.03213743e+01,  1.28145699e+01,  1.86398683e+00,
        3.33781956e+01,  2.86907964e-01,  4.64279918e+00, -7.44925273e-01,
        2.12048171e+01,  2.76452516e-01, -2.67509149e+00, -3.45496381e+00,
        1.53047889e+00,  7.58256411e+00,  4.30768162e+00,  5.39721282e+01,
        6.07815480e+00,  2.17179378e+00,  4.91875169e+00,  7.44100254e-01,
       -4.74490821e-01,  5.60930801e+01,  6.81330624e+00,  1.02090324e-01,
        1.81563193e+00,  2.78168465e+01,  1.16395801e+01,  1.97284083e+00,
        4.43838535e+00,  4.97704558e+00, -1.99603958e+00,  9.27424299e+00,
       -4.92419167e-01,  8.37526859e+01,  1.37705970e+01,  3.78236533e+01,
        1.38328555e+00, -1.60509579e+00,  1.45927081e+01,  7.22775182e+00,
        1.04219959e+01,  1.80651419e+01,  8.36093705e+00,  9.11090320e+00,
       -4.46728234e+00,  3.15926322e+00, -1.47015074e+00,  1.01360760e+02,
        1.72361744e+01,  1.32439890e+01,  7.86642160e+01,  1.55625616e+01,
        3.86864140e+00,  7.17895591e+00,  3.78282278e+00,  2.08637703e+01,
        1.70653060e+00,  1.60718311e+01,  5.22862052e+00,  8.36165577e+00,
        4.17160331e+00,  2.47923218e+01,  9.93697379e+00,  3.80733626e+00,
        1.87058774e+01,  2.49286903e+01,  7.02184653e+01, -1.81814403e+00,
        1.86934393e+01,  1.14773752e+01,  9.83279123e+00,  5.95475490e+00,
        5.59817220e+00,  5.05141171e-01, -6.68027312e+00, -2.55106914e+00,
        2.20647080e+01,  7.42425579e+01,  5.62522987e+00, -4.38790699e-02,
        1.17650088e+01,  9.96523058e+00,  8.83642816e+00,  5.60900192e+00,
        1.25060808e+01,  1.12574198e+01,  5.16902301e+01, -7.10633522e+00,
        2.67136731e+00,  2.23646254e+00,  6.76167692e+00,  1.41844945e+00,
        3.31297882e+00,  3.44952969e+01,  2.82730630e+00,  4.00207126e+00,
        2.95494485e+00, -1.30099645e+00,  6.45452634e+00,  7.42672890e+00,
        8.33783768e+00,  2.29853215e+00,  5.98282247e+00, -5.62059932e-03,
        2.19865098e+01,  3.54745397e+01,  3.09191128e+01,  1.41110494e+00,
        3.03310041e+00,  4.15121804e+00, -2.93416439e+00, -1.69391491e+00,
        1.51903041e+01,  3.45017581e+01, -3.66280405e+00,  1.02997272e+00,
       -1.67152632e+00,  3.18900379e+00,  2.97144056e+00,  1.22398106e+00,
        3.56965242e+00,  1.92214852e+01,  3.57732418e+00,  3.42467096e+00,
        4.11506214e-01,  1.61154221e+01,  1.90994298e+01,  8.00846918e+00,
        2.66879318e-01, -9.80970307e-01,  6.87398139e+00,  6.77519918e+00,
        4.10835713e-01,  3.89771198e+01,  1.16060543e+01,  3.69850185e+00,
       -2.37445587e+00,  1.03339344e+01,  7.01626724e+00,  1.42102016e+00,
        3.83071969e+00,  4.78151136e+01,  9.85075345e-01,  1.93046062e+01,
        2.56096027e+01,  5.47311467e+01,  1.94828141e+00,  6.55015840e+00,
        1.29287615e+02, -3.54735394e+00,  5.51208173e+00,  8.00610270e+00,
        9.36240924e+00,  1.64287712e+00,  1.12800575e+01, -2.50087816e+00,
        6.55765263e+00,  2.87779097e+01,  1.02825485e+00,  3.81250053e+00,
        2.25127981e+00,  1.87816623e+00, -7.40000435e+00,  2.08068007e+01,
        1.40115976e+01,  8.76570247e-01,  4.51616431e+00, -2.65084165e+00,
       -2.98443977e+00,  6.31757687e+00,  3.82598912e+00,  1.24980669e+01,
       -2.09920219e+00,  3.89204670e+00,  1.71451351e+01, -2.39077335e+00,
        1.21694190e+01,  1.44618395e+00,  6.43916226e+00,  4.20808577e+00,
        2.29435119e+00,  1.02283761e+01,  2.19479207e+01,  1.86547766e+01,
        2.00991804e+00, -5.72520124e-01,  1.89274475e+01,  7.18701507e+00,
       -1.28180815e+00, -2.14683130e+00,  6.68070204e+00,  8.80099337e+00,
        1.49173283e+01, -7.30505180e-01,  1.25375784e+00,  4.23242240e+00,
        6.98099665e+00,  5.40669350e+01,  8.08227947e+00, -8.31700376e-01,
        3.00060085e+01,  1.60466994e+00,  1.51540184e+01,  2.15143991e+02,
        5.68939427e-01,  1.44196403e+01,  1.02991366e+01,  1.28039873e+01,
        2.27834069e+00,  1.90196764e+00, -6.89687081e+00,  3.15491746e+01,
        5.66656020e+00,  4.02683920e+01,  1.39162637e+01,  3.50988212e+00,
        1.20903628e+00,  7.27272551e+00,  3.13376459e+00,  1.26728398e+03,
        1.51065170e+01,  1.20516968e+01,  5.82026926e-01, -2.32941103e-01,
        2.21816634e+00, -2.53995428e-01,  3.88798844e+01,  3.13461966e+00,
        4.57827254e+00,  2.49635570e+00,  1.19191636e+00, -4.91685130e-01,
        1.94399471e+01,  2.92321351e+00,  2.30656547e+01,  8.03882386e+00,
        8.71850040e+00,  1.47498425e+01,  2.27449423e+01,  4.80142318e+00,
        6.75633336e+00, -1.40596582e+00,  6.97713773e+00,  7.70411250e+00,
        9.67020819e+00, -1.95537268e+00,  5.82824611e+00,  1.16582774e+01,
       -1.81386358e+00,  2.23878299e+01,  2.51953618e+01,  2.82489923e+01,
        5.67332301e+00, -1.39204222e+00,  5.51222325e+00,  3.24044365e+01,
        1.12928463e+01,  1.30909128e+01,  1.13490407e+01, -6.78668944e+00,
        1.57746987e-01,  8.73057486e-01, -5.45369554e-02,  4.53831203e+00,
        1.77459944e+01,  3.87064378e+00,  2.57872255e+00,  2.48366412e+01,
        7.79579696e+00,  1.72717642e+00,  4.65409223e+01,  7.68075331e+00,
       -1.48643321e+00,  1.84520801e+00,  3.77991072e+00,  3.82901239e+00,
        1.64953866e+01,  1.10641415e+01, -2.07673881e+00,  5.93988830e+00,
        3.63239511e+00,  1.23891127e+02,  7.48773378e+00,  4.17831310e+00,
       -7.43684254e+00,  8.81425163e+00,  7.85765000e+01,  1.82987251e+00,
        2.32960001e+01,  6.39782275e-02,  1.78543846e+01,  1.22015154e+01,
        3.34446741e+01,  8.69555680e+00, -3.99429591e+00,  5.85166646e+00,
        1.68118584e+00,  3.28799650e-01, -5.73852261e+00,  8.85769840e+00,
       -7.40718459e-01,  1.93398200e+01,  6.05048342e-01, -4.27080820e-01,
        1.13326988e+01,  1.17598975e+01,  8.86251953e+00,  2.50331592e+00,
       -2.58347707e+00,  9.72229759e-01,  6.32525674e+00,  6.81827440e+00,
        1.29859157e+00,  1.24265890e+00, -5.95090290e-01, -3.96339827e+00,
       -1.59210675e+00,  9.34427469e+00,  1.24143398e+01,  3.26122276e+00,
        1.37174408e+00,  1.36980849e+01,  1.21751958e+01,  7.55107487e-02,
        1.55089847e+01,  8.34105274e+00,  5.10622312e+00,  5.39457031e+00,
        2.23595963e+00,  2.45112563e+01,  1.88224475e+00,  1.09635849e+01,
        6.19261934e-01,  1.46274466e+00, -9.91203020e-01, -2.97420764e+00,
        3.95244565e+01, -8.58205818e-01,  2.01568619e+00,  3.03242307e+00,
        5.66163870e-01,  1.04947648e+01,  1.98083235e+00,  5.61147365e+00,
        1.80007856e+01,  2.61976216e+01, -2.20904435e-01,  1.00252597e+01,
        1.03812549e+00,  2.79691943e+00, -6.08975744e+00,  4.79482070e+00,
        7.20080238e+01,  4.58720739e+00,  1.73760945e+01,  1.15912694e+02,
        1.62559676e+01,  4.72260849e+00,  1.26760376e+01,  2.93609182e+00,
        1.13534848e+01, -1.12024073e+00,  5.45220520e-01, -1.24808630e+00,
        9.19530866e+00,  3.21234167e+01,  1.39514035e+02,  2.74045923e+00,
        6.33699389e+00,  2.67136552e+00,  2.08032557e+00,  7.51176071e+00,
        1.45211119e+00,  2.30127878e+01,  4.13590861e+00,  3.93600511e+00,
        1.07751678e+00,  1.07247686e+01,  1.01351314e+01, -2.08707641e+00,
        4.11786577e+00,  2.60485513e+01, -5.51166795e-01,  3.82708882e+00,
        2.29783322e+01,  8.22234807e+00,  2.61676088e+00,  2.83685229e+01,
        1.36092370e+00,  1.39296112e+00,  2.26064841e+01,  7.00129826e+00,
       -6.20941369e-01,  1.27148244e+00, -2.36778426e+00, -5.35357858e+00,
       -4.43615529e+00,  3.39539436e-01,  6.04735129e+01, -1.06678757e+00,
        2.67981127e+00,  4.10182281e+00,  9.80970682e+00,  3.62718985e+00,
        2.44804683e+01,  1.59307283e+00,  1.49278770e+01,  2.49171707e+00,
        2.73347192e+00,  2.50671114e+00, -9.07831796e+00,  1.25972499e+01,
        3.83010049e+00,  4.68515098e+00,  8.50003631e-01,  3.43139360e+01,
        2.14032137e+00,  8.71366604e+00,  6.13462589e+00,  6.50467573e+00,
        7.15760867e+00,  8.97344969e+00,  1.35096162e+00, -1.15845314e+00,
       -8.15487518e-02, -1.70480120e+00,  7.84782537e+00,  1.52259843e+01,
        8.40850370e+00])

In [7]:
df['out2'] = hat_y**2
df['out3'] = hat_y**3
df['out4'] = hat_y**4
df

,capital,labour,output,wage,out2,out3,out4
0,2.606563,184,9.250759,43.080307,151.061183,1856.646929,2.281948e+04
1,1.323237,91,3.664310,27.780016,0.208942,0.095507,4.365659e-02
2,22.093692,426,28.781516,44.467748,1067.420235,34874.111139,1.139386e+06
3,10.737851,72,4.124642,39.734710,71.444670,603.885709,5.104341e+03
4,1.161365,46,2.890150,34.650709,1.322674,1.521175,1.749466e+00
...,...,...,...,...,...,...,...
564,2.625403,20,1.424376,33.477545,0.006650,-0.000542,4.422515e-05
565,1.276386,61,2.109048,26.300732,2.906347,-4.954744,8.446854e+00
566,1.953869,117,6.241870,41.153979,61.588363,483.334718,3.793126e+03
567,1.318527,46,7.902237,66.720139,231.830599,3529.849074,5.374543e+04
568,2.832391,161,6.804085,36.618435,70.702934,594.505886,4.998905e+03

In [11]:
model2=smf.ols(data=df, formula='output~capital+wage+labour+out2+out3+out4').fit()
model2.params

Intercept   -1.061334e+01
capital     -9.941387e-02
wage         3.498227e-01
labour       3.636213e-02
out2         6.738526e-03
out3        -1.633088e-05
out4         9.095123e-09
dtype: float64

In [9]:
R2_un = model2.rsquared
R2_re = model.rsquared

In [13]:
F_obs=(R2_un-R2_re)/(1-R2_un)*(len(df)-7)/3
F_obs

69.53250929274195

In [14]:
alpha = 0.05
stats.f.ppf(1-alpha,3,len(df)-7)

2.620761015118207

$$H_0 : \gamma_1=\gamma_2=\gamma_3=0$$
$$H_1 : \gamma_1^2+\gamma_2^2=\gamma_3^2>0$$

$ F_{obs} > F_{cr} \Rightarrow H_0$ Ð¾Ñ‚Ð²ÐµÑ€Ð³Ð°ÐµÐ¼

# 1.1

In [18]:
df = pd.read_csv('https://raw.githubusercontent.com/ryupepa/Econometrica/master/python-notebooks/data-csv/sleep75.csv')
df

,age,black,case,clerical,construc,educ,earns74,gdhlth,inlf,leis1,...,spwrk75,totwrk,union,worknrm,workscnd,exper,yngkid,yrsmarr,hrwage,agesq
0,32,0,1,0.000000,0.000000,12,0,0,1,3529,...,0,3438,0,3438,0,14,0,13,7.070004,1024
1,31,0,2,0.000000,0.000000,14,9500,1,1,2140,...,0,5020,0,5020,0,11,0,0,1.429999,961
2,44,0,3,0.000000,0.000000,17,42500,1,1,4595,...,1,2815,0,2815,0,21,0,0,20.529997,1936
3,30,0,4,0.000000,0.000000,12,42500,1,1,3211,...,1,3786,0,3786,0,12,0,12,9.619998,900
4,64,0,5,0.000000,0.000000,14,2500,1,1,4052,...,1,2580,0,2580,0,44,0,33,2.750000,4096
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
701,45,0,702,0.182331,0.030075,12,5500,1,0,5069,...,1,2026,0,2026,0,27,0,18,NaN,2025
702,34,0,703,0.182331,0.030075,10,2500,0,0,5885,...,0,675,1,465,210,18,0,4,NaN,1156
703,37,0,704,0.182331,0.030075,12,3500,1,0,4719,...,1,1851,0,1851,0,19,0,17,NaN,1369
704,54,0,705,0.182331,0.030075,17,32500,1,0,5149,...,1,1961,1,1481,480,31,0,22,NaN,2916
705,30,0,706,0.182331,0.030075,16,6750,1,0,4747,...,0,2363,0,2363,0,8,1,9,NaN,900

In [21]:
model = smf.ols(data=df, formula='sleep~totwrk+age++male+smsa+south').fit()
hat_y=model.predict()

In [22]:
hat_y

array([3067.10583631, 2894.49476254, 3150.37075855, 2910.94924531,
       3303.75993003, 3472.6900719 , 3301.14172725, 3023.8804497 ,
       3251.79465914, 3104.60304347, 2591.50610935, 3415.84208454,
       3157.91546836, 3239.22243895, 3168.41882119, 3124.69052876,
       3124.03220455, 2983.72677965, 3263.51683965, 3369.7221562 ,
       3044.02875134, 3060.57363178, 3285.21066833, 3135.81565247,
       2807.46105408, 3101.03250584, 3002.42541199, 3129.80523542,
       3214.60758145, 3188.66233468, 2991.99642153, 3018.92151018,
       3136.97517574, 3199.27100653, 3074.11687847, 2978.93503636,
       3180.58032354, 3450.79249364, 3119.08529912, 3152.00332795,
       3122.41382707, 3150.48016232, 3167.61968067, 3243.68584648,
       3168.42290594, 3243.74401963, 3220.49507817, 3498.46452305,
       3299.07444219, 2768.41983181, 3036.14254043, 3096.3245862 ,
       3227.14627219, 3133.77301111, 3173.5133905 , 3232.01790829,
       3266.75411605, 3224.56832679, 3228.83170859, 3226.16578442,
       3042.22097012, 3197.73429487, 3250.013365  , 3266.25307091,
       3311.20090314, 3474.34197885, 3156.88642263, 2892.63359288,
       3134.63372687, 3480.67365249, 3095.41115735, 3075.25648869,
       3195.8865877 , 3463.83074705, 3130.45409835, 3196.60424578,
       3242.42051883, 3159.70973302, 3333.3342485 , 3213.96760429,
       3319.79895115, 3666.47965375, 3357.19874772, 3137.155918  ,
       3188.51834058, 3170.89302988, 3434.61048522, 2958.67562419,
       3231.54898782, 3411.71459359, 3180.90979055, 3260.78279568,
       3253.59850953, 3293.49858688, 3277.80007636, 3338.01716353,
       3325.20357955, 3132.6159362 , 3114.68837499, 2958.73795247,
       3207.50390025, 3144.72620793, 3089.14181198, 3158.88558789,
       3375.95633572, 3153.058332  , 3137.65132555, 3460.34067775,
       3408.44215134, 3165.11758012, 3387.52499047, 3048.04928688,
       3082.35707564, 3352.43164813, 3412.96536841, 3111.14728208,
       3130.00818518, 2852.13217915, 3181.08625324, 3165.91259498,
       3320.58292242, 3390.50728668, 3375.34035636, 3110.74300163,
       3067.10905501, 3330.31657944, 3256.19888672, 3449.23969261,
       3411.19977812, 2959.93910846, 3188.99395952, 3167.91231598,
       3060.27875511, 3308.50849189, 2999.89617847, 2956.25035167,
       3370.00178009, 3495.90464733, 3473.15748044, 3150.44348454,
       3302.79048586, 3338.40547905, 3307.32251832, 3241.55114159,
       3205.20464231, 3191.04779839, 3159.33633885, 3222.35237107,
       3206.5522113 , 2871.81629096, 3029.56965691, 3159.60498951,
       3210.33531389, 3299.65057914, 3486.86239291, 3042.21135493,
       3649.36027275, 2986.4199907 , 3128.28055785, 3179.1138895 ,
       3292.60607789, 3279.91450728, 3168.54025905, 3418.30361324,
       3455.87123464, 3045.79952333, 3169.19082875, 3035.42893032,
       3249.84394469, 3167.12820395, 3161.08168463, 3281.51297171,
       3068.73231704, 3134.71675071, 3450.42234764, 3278.07977063,
       3102.73077613, 3184.8558098 , 3155.30865377, 3237.99479588,
       3290.9773027 , 3351.9217703 , 3317.91127712, 3238.38810311,
       3253.42098597, 3290.31318698, 2979.16043522, 3416.29135302,
       3272.7102377 , 3294.60630402, 3299.22316693, 3365.8453537 ,
       3214.5269765 , 3460.10339872, 3193.81215311, 3284.33099324,
       3195.31684725, 3339.76250932, 3335.57406541, 3177.52597669,
       3377.12237993, 3512.73021252, 3291.72459619, 3124.14240813,
       3356.74626054, 3210.40237281, 3270.19935123, 3192.12664633,
       3115.99118023, 3221.65854957, 3304.31438092, 3321.30286278,
       3032.36416848, 3293.40272914, 3322.07565285, 3283.53469321,
       3167.93605271, 3278.85515079, 3193.36848131, 3207.80366148,
       3144.66146075, 3171.7840564 , 3468.23728637, 3269.84687691,
       3158.16966604, 3185.36820637, 3119.56243   , 3368.12693994,
       3205.31102221, 3225.36497804, 3172.25967534, 3302.28944072,
       3250.10922274, 3209.71998042, 3131.16941522, 3263.43842199,
       3070.96587408, 3212.95094387, 3255.78166522, 2995.4001779 ,
       3278.42335918, 3031.41006064, 3287.79019604, 3132.03164292,
       3168.43815873, 3390.11340394, 3272.93805545, 3231.54898782,
       3346.09129571, 3217.18086658, 3246.47806359, 3306.84130269,
       3096.17843427, 3254.68920087, 3459.42085242, 3177.93926735,
       3330.62507252, 3248.00274116, 3430.23412004, 2902.35290406,
       3153.04141336, 3137.75528654, 3218.87984901, 3229.78828209,
       3324.21836114, 3322.48478838, 3220.21860261, 3186.35184246,
       3643.69744546, 3349.01599428, 3184.20388208, 3532.84010015,
       3292.75953327, 3284.60736895, 3202.11203537, 3196.66347981,
       3307.78919743, 3244.44639546, 3264.28305569, 3331.94690747,
       3446.55375554, 3257.21290395, 3350.92267442, 3342.9305395 ,
       3159.45384587, 3436.9406998 , 3247.12850884, 2985.76060562,
       3384.73032498, 3172.81101467, 3287.79341474, 3460.03618589,
       3323.4829773 , 3396.34448921, 3301.59585081, 3288.92993071,
       3090.65460938, 3225.7071545 , 3439.93991466, 3371.45939873,
       3283.97205205, 3278.23080711, 3608.44927242, 3084.68880216,
       3689.1309629 , 3076.82836619, 3515.24036957, 3184.83904507,
       3416.97696411, 3300.08630159, 3060.29551984, 3129.43841526,
       3174.88718549, 3375.62634727, 3139.65162206, 3278.24757184,
       3376.23608405, 3489.16962965, 3595.04238495, 3232.07319419,
       3057.92920298, 3310.34091681, 3275.81567854, 3129.51766219,
       3213.23378646, 3284.98043168, 3251.53331193, 3194.44724572,
       3169.7805821 , 3414.82884982, 3242.85787767, 3215.25966308,
       3272.01108058, 3031.26606653, 3204.73954553, 3320.27601166,
       3126.47031097, 3246.08948701, 3571.60887754, 3538.54134145,
       3386.83445804, 3481.84286134, 3124.07213051, 3212.04713022,
       3212.4617789 , 3238.73327398, 3348.64044228, 3222.45295945,
       3091.98699595, 3115.15427159, 3248.47896508, 2968.72182957,
       3411.37430727, 3403.24363833, 3240.70328919, 3551.83927622,
       2926.6894957 , 3163.55358158, 3387.21493138, 3308.45646147,
       3167.36306409, 3265.49136121, 3173.86737675, 3374.26065553,
       3145.19210453, 3262.57692372, 3244.57520714, 3331.39061321,
       3265.68008228, 3103.42031806, 3199.08955213, 3229.37763462,
       3411.2334615 , 3563.73318878, 3351.48547233, 3141.19794891,
       3432.51097565, 3340.43135568, 3278.87400298, 3395.03375192,
       3501.47483557, 3549.73976665, 3184.79514737, 3162.47224436,
       3140.38919319, 3236.72431599, 3155.24863723, 3335.91450564,
       3179.16826844, 3348.32380917, 3111.19364543, 3199.02642405,
       3252.66426067, 3224.71305032, 3220.60843007, 3140.25814014,
       3325.17329826, 3405.77853891, 3284.56505357, 3054.40654065,
       3592.2109713 , 3233.92650219, 3245.24405351, 3112.61451592,
       3507.99443049, 3294.92025717, 3180.71144697, 3525.64760359,
       3156.67851793, 3058.13053366, 3379.439831  , 3216.36969197,
       3296.8071314 , 3447.46081736, 3214.40936232, 3471.90776649,
       3211.72909232, 3172.98354653, 3187.21648906, 3248.45338497,
       3052.31666989, 3140.32686491, 3252.40133114, 3395.82652542,
       3328.85729494, 3106.2141175 , 3082.19389791, 3520.89846621,
       3085.90521094, 3098.56775843, 3670.08008054, 3544.23454987,
       3391.40659399, 3214.612466  , 3312.87246207, 3129.69885552,
       3213.32249466, 3315.00077046, 3214.20561275, 3323.22477841,
       3386.22147309, 3181.54011574, 3260.93946977, 3260.90030271,
       3737.26499484, 3177.13373034, 3196.44754223, 3177.20078926,
       3146.84401147, 3197.40331593, 3241.90270895, 3274.41266312,
       3163.76543441, 3150.91252945, 3405.31723634, 3204.58151341,
       3236.01936736, 3286.36610686, 3341.9307142 , 3159.52669631,
       3195.30008252, 3170.37522   , 3417.73062462, 3397.86516556,
       3558.10310844, 3165.1214038 , 3171.60180219, 3532.62038565,
       3240.93274333, 3242.43743747, 3144.02463191, 3191.36258812,
       3565.18680621, 3344.5695054 , 3375.83562729, 3173.58211527,
       3554.98074896, 3104.88115541, 3382.81085772, 3404.37121445,
       3261.70905843, 3422.65088906, 3209.19406729, 3321.08707912,
       3077.80427723, 3573.93924603, 3557.98469446, 3174.8186441 ,
       3299.54499905, 3434.72383712, 3135.27785916, 3471.70308049,
       3742.92782213, 3579.34387443, 3234.24280386, 3517.8240524 ,
       3195.86267343, 3303.39133688, 3312.542544  , 3393.20458248,
       3484.48635371, 3562.35539257, 3362.21328759, 3265.94306588,
       3530.29017107, 3277.9470281 , 3334.46577275, 3471.53543319,
       3640.34500324, 3501.47483557, 3631.26989473, 3402.15419786,
       3405.06943515, 3396.41076562, 3483.8887214 , 3277.16707121,
       3399.24217926, 3396.41076562, 3478.03153544, 3438.23204647,
       3545.68743788, 3429.11130402, 3479.37180097, 3354.03220001,
       3376.67147506, 3478.21378964, 3447.04996289, 3183.99119267,
       3490.149181  , 3535.58269844, 3646.00783053, 3580.88531673,
       3242.13767624, 3460.1713646 , 3389.75461667, 3272.31299964,
       2991.26202818, 3078.97095004, 3685.44371805, 3549.73976665,
       3092.5885591 , 3496.20924635, 3329.55114591, 3203.47228434,
       3131.99171696, 3546.77745387, 3239.52204626, 3096.8655573 ,
       3234.79902775, 3108.57801545, 3309.79672701, 3017.20254431,
       3266.22590847, 2942.88829831, 3126.62376635, 3228.02617157,
       3845.26779475, 3055.06425988, 3366.36804813, 3102.57732075,
       3538.41411208, 3434.89821236, 3492.98059464, 3256.51052812,
       3429.81367985, 3225.92120194, 3267.68594601, 3445.8584221 ,
       3267.10973869, 3236.15927671, 3123.24816291, 3456.55590931,
       3466.97543849, 3492.80972864, 3283.37593167, 3174.88718549,
       3649.89651321, 3322.66613563, 3208.14243585, 3401.05851481,
       2996.83452817, 3094.0893224 , 3242.32314915, 3468.47620179,
       3281.91646965, 3115.8678817 , 3312.85569734, 3194.77413992,
       3184.24456108, 3335.54375465, 3825.44789925, 3320.54761996,
       3290.01997616, 3230.56917541, 3255.69144508, 3259.07435197,
       3151.35854977, 3415.52433717, 3246.89122981, 3131.63209311,
       3229.06914154, 3311.28945743, 3541.83054843, 3327.60100697,
       3251.36888333, 2848.57200976, 3255.20228011, 3382.44161867,
       3322.35067054, 3567.21252893, 3252.27179002, 3286.25197245,
       3382.36783181, 3555.997339  , 3411.36053696, 3403.03416762,
       3518.84379077, 3089.87298663, 3345.53265292, 3076.85152741,
       3007.94118038, 3563.76593573, 3613.28242414, 3082.28653695,
       3092.62208856, 3407.3648694 , 3419.78272726, 3410.01875948,
       3227.08882846, 3497.79094604, 3257.16582846, 3153.74163135,
       3518.45536809, 3630.10863523, 3180.4844658 , 3075.55939824,
       3179.86118299, 3572.91210438, 3118.1918537 , 3244.33226104,
       3240.10706897, 3130.62673736, 3271.85913713, 3384.24267195,
       3102.2487607 , 3541.24552572, 3219.41457753, 3293.19897957,
       3152.48197077, 3295.34478212, 3220.55740645, 3332.69235757,
       3236.32718508, 2952.68670251, 3515.20684011, 3211.6620334 ,
       3044.06379274, 3317.38458148, 3032.74135687, 3084.46908766,
       3498.64342193, 3366.03800561, 3249.12873497, 3495.45722223,
       3196.05696173, 3123.16585119, 3465.08061491, 3238.17705009,
       3226.65816809, 3266.68869352, 3323.70921274, 3343.94455673,
       3186.48058377, 3170.72920626, 3180.53324805, 3208.04657811,
       3133.28873069, 3088.10050787, 3221.71448136, 3055.84251001,
       3266.34825329, 3483.94715562, 3172.90214178, 3382.02981048,
       3336.60983908, 3535.58269844, 3202.41728028, 3446.70479203,
       3266.16126845, 3197.0510659 , 3169.94989525, 3301.17525671,
       3260.20507642, 3227.45398276, 3258.53640475, 3232.23611085,
       3184.11899756, 3345.40705994, 3329.95149552, 3270.58377269,
       3197.32917785, 3196.24867721, 3543.0868364 , 3260.14505988,
       3389.06343835, 3252.6810254 ])

In [31]:
df['slp2'] = hat_y**2
df['slp3'] = hat_y**3
df['slp4'] = hat_y**4
df['slp2']/3600

0      2613.093948
1      2327.249981
2      2756.898866
3      2353.784864
4      3031.897132
          ...
701    2837.779335
702    3487.073425
703    2952.373837
704    3190.486386
705    2938.870515
Name: slp2, Length: 706, dtype: float64

In [32]:
model2=smf.ols(data=df, formula='sleep~totwrk+age++male+smsa+south+slp2+slp3+slp4').fit()
model2.params

Intercept   -3.820997e-04
totwrk      -6.838277e-03
age          2.731616e-01
male         1.417045e+00
smsa        -2.967532e+00
south       -2.989736e+00
slp2         5.111848e-04
slp3        -2.871411e-08
slp4        -1.028501e-11
dtype: float64

In [33]:
R2_un = model2.rsquared
R2_re = model.rsquared

In [34]:
F_obs=(R2_un-R2_re)/(1-R2_un)*(len(df)-9)/3
F_obs

0.5550316084175276

In [35]:
alpha = 0.05
stats.f.ppf(1-alpha,3,len(df)-6)

2.6176267081917324